### PR TITLE
fix leak workspaces vcs_repo.branch on import 

### PR DESCRIPTION
**Pull request by kuroseets**
## Description

This PR is a fix to drop VCS repository's branch name when importing workspace.

### CODE REVIEW

**Comment by kuroseets** [comment]
I changed title because I don't deal data source.

**Comment by kuroseets** [comment]
issue #208

**Comment by kuroseets** [comment]
i close this and request again

**Comment by koikonom** [comment]
Hi @kuroseets, 

Thanks for opening this PR. I  pulled your change in PR #220, and it was merged to master today. The fix will be included in the next provider release.

**Comment by kuroseets** [comment]
Thank you very much:)

**Pull request closed without merging**
