### PR TITLE
Add speculative_enabled argument to tfe_workspace

### LINKED ISSUE #211: Add speculative_enabled argument to tfe_workspace
We would like to be able to set the `speculative-enabled` attribute on a workspace (see [API doc](https://www.terraform.io/docs/cloud/api/workspaces.html)).

This attribute could be exposed as the `speculative_enabled` argument to `tfe_workspace`.

#210 implements that feature.

hashicorp/go-tfe#133 is the related issue on the `go-tfe` library, and hashicorp/go-tfe#132 is the related PR.

### PR DESCRIPTION
**Pull request by jgiannuzzi**
## Description

* [x] **Requires a go-tfe release with hashicorp/go-tfe#132** -> go-tfe v0.10.2 has been released

This change adds support for the `speculative_enabled` argument to `tfe_workspace`.

Fixes #211

## Testing plan

The tests have been updated to test this in the same way that `file_triggers_enabled` is tested.
`file_triggers_enabled` also defaults to `true` during workspace creation and is thus quite comparable.

## External links

- [API documentation](https://www.terraform.io/docs/cloud/api/workspaces.html)

## Output from acceptance tests

```
$ TESTARGS="-run TestAccTFEWorkspace" make testacc
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccTFEWorkspace -timeout 15m
?   	github.com/terraform-providers/terraform-provider-tfe	[no test files]
=== RUN   TestAccTFEWorkspaceIDsDataSource_basic
--- PASS: TestAccTFEWorkspaceIDsDataSource_basic (10.96s)
=== RUN   TestAccTFEWorkspaceIDsDataSource_wildcard
--- PASS: TestAccTFEWorkspaceIDsDataSource_wildcard (10.31s)
=== RUN   TestAccTFEWorkspaceDataSource_basic
--- PASS: TestAccTFEWorkspaceDataSource_basic (8.54s)
=== RUN   TestAccTFEWorkspace_basic
--- PASS: TestAccTFEWorkspace_basic (6.75s)
=== RUN   TestAccTFEWorkspace_panic
--- PASS: TestAccTFEWorkspace_panic (7.31s)
=== RUN   TestAccTFEWorkspace_monorepo
--- PASS: TestAccTFEWorkspace_monorepo (7.28s)
=== RUN   TestAccTFEWorkspace_renamed
--- PASS: TestAccTFEWorkspace_renamed (9.51s)
=== RUN   TestAccTFEWorkspace_update
--- PASS: TestAccTFEWorkspace_update (10.76s)
=== RUN   TestAccTFEWorkspace_updateWorkingDirectory
--- PASS: TestAccTFEWorkspace_updateWorkingDirectory (15.61s)
=== RUN   TestAccTFEWorkspace_updateFileTriggers
--- PASS: TestAccTFEWorkspace_updateFileTriggers (11.14s)
=== RUN   TestAccTFEWorkspace_updateTriggerPrefixes
--- PASS: TestAccTFEWorkspace_updateTriggerPrefixes (11.02s)
=== RUN   TestAccTFEWorkspace_updateSpeculative
--- PASS: TestAccTFEWorkspace_updateSpeculative (11.02s)
=== RUN   TestAccTFEWorkspace_updateVCSRepo
    TestAccTFEWorkspace_updateVCSRepo: resource_tfe_workspace_test.go:372: Please set GITHUB_TOKEN to run this test
--- SKIP: TestAccTFEWorkspace_updateVCSRepo (0.54s)
=== RUN   TestAccTFEWorkspace_sshKey
--- PASS: TestAccTFEWorkspace_sshKey (16.25s)
=== RUN   TestAccTFEWorkspace_import
--- PASS: TestAccTFEWorkspace_import (7.26s)
PASS
ok  	github.com/terraform-providers/terraform-provider-tfe/tfe	144.541s
?   	github.com/terraform-providers/terraform-provider-tfe/version	[no test files]
```

### CODE REVIEW

**Comment by jgiannuzzi** [comment]
Hey @koikonom, I had to force push my commit to bump go-tfe to v0.10.2. I did the update on Linux so that the vendor dir would not dramatically change.

This PR is now ready for review! 😄

**Comment by koikonom** [comment]
Yeah you had to force push because I pushed the same change myself :)

**Comment by jgiannuzzi** [comment]
Thanks for the merge, @koikonom!

**Comment by jgiannuzzi** [comment]
Hey @koikonom, we would love to be able to use this new feature in an official build — could you please create a new release soon? Thanks! 🙏

**Pull request merged**
